/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class register_StaticRegister */

#ifndef _Included_register_StaticRegister
#define _Included_register_StaticRegister
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     register_StaticRegister
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_register_StaticRegister_hello
        (JNIEnv *, jobject);

JNIEXPORT jstring JNICALL Java_string_StringTest_sayHello
        (JNIEnv *, jclass, jstring);


JNIEXPORT void JNICALL Java_clz_FieldTest_getField
        (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_clz_FieldTest_getStaticField
        (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_clz_MethodTest_nativeCallStaticMethod
        (JNIEnv *env, jobject jObj, jstring jStr, jint jInt);

JNIEXPORT void JNICALL Java_clz_MethodTest_nativeCallInstanceMethod
        (JNIEnv *env, jobject jObj, jstring jStr, jint jInt);

JNIEXPORT jstring JNICALL Java_clz_MethodTest_nativeCallInstanceMethod1
        (JNIEnv *env, jobject jObj, jstring jStr, jint jInt);


JNIEXPORT jstring JNICALL Java_ref_Reference_newString
        (JNIEnv *env, jobject jObj, jint jInt);

JNIEXPORT void JNICALL Java_ref_Reference_JCall
        (JNIEnv *env, jobject jObj);
#ifdef __cplusplus
}
#endif
#endif
